services:

    Goat\Query\Symfony\Twig\ProfilerExtension:
        public: false
        tags: ['twig.extension']

    Goat\Query\Symfony\DataCollector\ConnectionDataCollector:
        public: false
        arguments: ["@goat.runner.default", '@?debug.stopwatch']
        tags: [{name: data_collector, template: "@Goat/profiler/goat.html.twig", id: goat_runner}]
